name: Build, test, check style and deploy JAR to artifacts

on:
  push:
    branches:
      - acceptance

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run tests with Maven
        run: mvn -B package test --file pom.xml

      - name: Check Code Style
        run: mvn checkstyle:check

      - name: Upload JAR files
        run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging
        
