name: Build and test with maven

on:
  push:
  pull_request:
    branches: [ "main", "acceptance", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Find image file
        run: |
          find . -name "Jabberpoint.gif" -exec cp {} . \;

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run tests with Maven
        run: mvn -B package test --file pom.xml
